### PR TITLE
setup favicon for app

### PR DESCRIPTION
**Pull request by RocktimSaikia**
## Types of changes

- [x] feature (change which adds functionality)

## Purpose

This app currently doesn't have a favicon as per #86. It would be a nice addition for app recognition.

## Approach

Added a 16x16 beer mug `.ico` file for the app's favicon. 

## Screenshot(s)

favicon add

## Checklist

- [x] My branch follows the branch naming scheme of BreweryFinder (ref. readme), and can be merged into `master` without error.
- [x] My code follows the code style of this project, and I have linted it to confirm this by running `npm run lint`.
- [x] All new and existing tests passed. I have confirmed this by running `npm test`.

## Link to Issue

[#86](https://github.com/JasonFritsche/BreweryFinder/issues/86)

### CODE REVIEW

**Comment by cdrani** [comment]
@RocktimSaikia: Looks Good To Me. Pay a little attention to PR template. The template was included to make PR and issues more informative and easy to read the extent of the changes it makes to the codebase. Additionally, this will be great practice for bigger projects which will enforce that the PR/issue templates are adhered to or else they will be automatically closed. 

I have updated your PR to keep it line with the template. It's still clean, but very communicative of your work and taking the time to go through the checklists makes a code review easier as I will be more trustworthy of the PR, and thus not need to go through the steps myself to ensure the PR doesn't introduce a regression in the code.

I am willing to accept this PR as it addresses the issue, but can I ask why you used a different image than the current one? For continuity the favicon is usually the same as the brand logo. However, it's not a big deal here. Thanks for your PR!

**Comment by RocktimSaikia** [comment]
@cdrani  Hey . Actually i tried to use the logo as favicon but it did not look very clear due to the two cup images.So i used a this new clean favicon. Anyway there is a very odd issue i am noticing which is that when i used the favicon in my development setup it worked great even now its working fine.But now when i accessed the site, i don't see the favicon.Can you recheck the site and tell me its working fine. If you are seeing the favicon in your PC then its just my browser cache that making this issue.

**Comment by cdrani** [comment]
That's fine, I guess. As for the missing favicon on the site, I seem to have forgotten to deploy the new built. It should work now.

**Comment by RocktimSaikia** [comment]
@cdrani that makes sense

**Pull request merged**
