### PR TITLE
Issue #3: Filter out all instances of "Brewery in Planning" 

### PR DESCRIPTION
**Pull request by mytuny**
Issue #3 got solved!

### CODE REVIEW

**Comment by JasonFritsche** [comment]
The filter method looks good, but it still needs to be implemented in the BreweryList component.

**Comment by mytuny** [comment]
Well, I think we don't need to update the BreweryList component since the solution were injected right after consuming the HTTP request from the API and before updating the state. Since BreweryList generate the list from the items element of the state :) :+1:

**Comment by mytuny** [comment]
Oops! hhh funny .. I was writing my prev. comment when you say it's fine ^^

**Comment by JasonFritsche** [comment]
You're absolutely right. I just merged the request. Feel free to contribute
to other issues if you'd like.

**Pull request merged**
