### PR TITLE
Add style to initial Page issue #4

### PR DESCRIPTION
**Pull request by SahibArora**
Hi have tried to style it. 
Please give it look, I have styled first page/ main page.
If you would like  I can work further with the same style.
Thanks!

### CODE REVIEW

**Comment by SahibArora** [comment]
This is how it looks now:
image

Earlier:
image

Thanks,

**Comment by JasonFritsche** [comment]
@SahibArora  Can you add more contrast on the text/fonts? It's difficult to read the radio button text.

**Comment by SahibArora** [comment]
Sure, I will increase the contrast soon.
and yes, the photo is being taken from the `unsplash.com`. So, Its free to use. 
Thanks,

**Comment by SahibArora** [comment]
Hi there,
I made the buttons more readable. Please have a look!
Thanks,

**Comment by JasonFritsche** [comment]
@SahibArora I appreciate the effort, but I just ran this locally and the text is still difficult to read. I do like the picture though. I can't merge this PR at this time though based on the text being difficult to read.

**Comment by SahibArora** [comment]
Its all good, I tried!
Thanks,

**Comment by JasonFritsche** [comment]
@SahibArora  What about another image? something that is easier to use with text?

**Comment by SahibArora** [comment]
Image change - looks a good Idea, Please have a look, what do you think of this one.
Thanks,

Now:
image

**Comment by JasonFritsche** [comment]
@SahibArora I like this image. I will merge this PR, but will leave the Style Issue open under issues, as it is an ongoing ticket where others can come in and manipulate the style. Nothing is set in stone in this project. I appreciate your contributions to the project.

**Comment by SahibArora** [comment]
Sure, sounds good.
Thanks,

**Pull request merged**
