### PR TITLE
Add responsive design

### PR DESCRIPTION
**Pull request by chrisdesilva**
Fixed the horizontal scroll by removing margin and padding from a few rows, centered the radio buttons, set logo to hidden on small devices

### CODE REVIEW

**Comment by JasonFritsche** [comment]
I had some conflict with the package-lock.json file. Your changes were merged. Thanks for your contribution.

**Comment by cdrani** [comment]
@chrisdesilva: Could you please create a different branch from your fork's master branch, make the commits towards resolving an issue, push that branch up to your fork, and then make a PR?

As it stands, you are working off of one branch (master) and all your commits, even the previous ones are included in the PR. The PR should only create commits that affect the issue. Please reference the instructions in the project readme. Your fork needs to have a master branch which you keep updated with this project's master branch before you create any branches off of master for PRs. This will greatly help in lessening the amount of merge conflicts as your branches will be at or close to the source of truth, i.e the project's master branch.

This [article](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/) greatly helped me when I first started contributing as well, which is why a similar version of it is on the readme. 

I just want to say it is not your fault, as maybe the readme isn't being read or there isn't any references to it, but a fix is incoming. Hopefully setting up github templates and a well documented contributing guide will help here.

**Comment by cdrani** [comment]
I guess it was merged before I finished my comment, but please consider what I wrote above as it is good practice and part of the github workflow. Thanks @chrisdesilva!

**Comment by JasonFritsche** [comment]
Thanks for pointing out best practices @cdrani . I went ahead and merged in the changes. @chrisdesilva  Please review Charles' comment regarding any future work on the project. Also, I look forward to seeing more PR's. Thanks!

**Comment by cdrani** [comment]
@JasonFritsche: I don't see any changes that the merge should have addressed:
> Fixed the horizontal scroll by removing margin and padding from a few rows, centered the radio buttons, set logo to hidden on small devices

There's also no reference to this PR merge in the commit history.

**Comment by chrisdesilva** [comment]
Thanks @cdrani for the advice! Sorry if that caused some headaches.

**Comment by JasonFritsche** [comment]
I'll have to take a look. There were some conflicts with the
package-lock.json file so I merged the changes on my local. If there's
still responsiveness issues we can reopen the issue.

**Pull request closed without merging**
