### PR TITLE
remove url and isLoaded out of state

### PR DESCRIPTION
**Pull request by cdrani**
- fix form submission canceled because the form is not connected warning
- replace isLoaded state with React.Suspense and fallback
- remove url from state and refactor fetchBreweryData to accept searchTerm and searchParm args
- run npm audit fix to update dependencies with vulnerabilities warnings

refs #23

### CODE REVIEW

**Comment by JasonFritsche** [comment]
@cdrani I like what you did here. The empty search handles much better. I did notice one issue when I ran this locally, when I run a search there's maybe half a second to a second where the "sorry we couldn't find..." message gets displayed, then the results get displayed.

**Comment by cdrani** [comment]
Hmm... could you try again? Maybe I was out of sync with master, because after pulling I don't see that message.

**Comment by JasonFritsche** [comment]
I will try later today. Thanks Charles.

**Comment by JasonFritsche** [comment]
Awesome. Everything works well. Thanks for your contribution.

**Pull request merged**
